---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-<name>
  labels:
    type: mysql-<name>
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/data/<name>"
---
